// ============================================================
// 環境場址調查成果平台 Demo v1
// ============================================================

// ============================================================
// 1. 建立 Leaflet 地圖
// ============================================================
const map = L.map("map").setView([25.0330, 121.5654],16);

// ============================================================
// 2. Google Satellite 衛星底圖
// ============================================================
L.tileLayer("https://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}",{
    maxZoom:20,
    subdomains:["mt0","mt1","mt2","mt3"],
    attribution:"Map data © Google"
}).addTo(map);

// ============================================================
// 3. 建立地下水監測井圖示
// ============================================================
const monitoringWellIcon=L.divIcon({className:"monitoring-well-marker",html:`<div class="mw-symbol"><div class="mw-inner"></div></div>`,iconSize:[24,24],iconAnchor:[12,12],tooltipAnchor:[0,-14]});

// ============================================================
// 4. 讀取調查資料
// ============================================================
fetch("data/samples.json").then(response=>{if(!response.ok)throw new Error("無法讀取 samples.json");return response.json();}).then(data=>{
 document.getElementById("site-description").textContent=`${data.site.name}｜${data.site.project}`;
 const allCoordinates=[];
 data.sampling_points.forEach(point=>{const coordinate=[point.latitude,point.longitude];allCoordinates.push(coordinate);const marker=L.marker(coordinate).addTo(map);marker.bindTooltip(point.id,{permanent:true,direction:"top"});marker.on("click",()=>showSoilPointDetail(point));});
 if(data.monitoring_wells){data.monitoring_wells.forEach(well=>{const coordinate=[well.latitude,well.longitude];allCoordinates.push(coordinate);const marker=L.marker(coordinate,{icon:monitoringWellIcon}).addTo(map);marker.bindTooltip(well.id,{permanent:true,direction:"top",className:"mw-tooltip"});marker.on("click",()=>showMonitoringWellDetail(well));});}
 if(allCoordinates.length>0)map.fitBounds(allCoordinates,{padding:[50,50],maxZoom:18});
}).catch(error=>console.error("讀取調查資料失敗：",error));

// ============================================================
// 8. 顯示土壤調查點資料
// ============================================================
function showSoilPointDetail(point){
 showDetailPanel();document.getElementById("point-id").textContent=point.id;document.getElementById("point-type").textContent=`${point.type}｜地表高程 EL. ${point.ground_elevation??"—"} m`;const container=document.getElementById("sample-results");container.innerHTML="";
 const standards={"TPH":1000,"苯":5,"甲苯":500,"TCE":60};const analytes=[];point.samples.forEach(sample=>{Object.keys(sample.results).forEach(name=>{if(!analytes.includes(name))analytes.push(name);});});
 const title=document.createElement("h3");title.textContent="土壤分析結果（mg/kg）";container.appendChild(title);const tableWrapper=document.createElement("div");tableWrapper.className="table-wrapper";const table=document.createElement("table");table.className="result-table large-result-table";const thead=document.createElement("thead");const headerRow=document.createElement("tr");headerRow.innerHTML=`<th>樣品編號</th>`+analytes.map(name=>`<th>${name}</th>`).join("");thead.appendChild(headerRow);const standardRow=document.createElement("tr");standardRow.className="standard-row";standardRow.innerHTML=`<th>土壤污染<br>管制標準</th>`+analytes.map(name=>{const standard=standards[name];return `<th>${standard!==undefined?standard.toLocaleString():"—"}</th>`;}).join("");thead.appendChild(standardRow);table.appendChild(thead);const tbody=document.createElement("tbody");
 point.samples.forEach(sample=>{const row=document.createElement("tr");const sampleName=`${point.id}(${formatDepth(sample.depth_from)}–${formatDepth(sample.depth_to)})`;let html=`<td class="depth-cell">${sampleName}</td>`;analytes.forEach(name=>{const result=sample.results[name];if(!result){html+=`<td class="no-data">—</td>`;return;}const value=result.value;const standard=standards[name];const exceed=standard!==undefined&&typeof value==="number"&&value>standard;if(exceed){const ratio=value/standard;html+=`<td class="exceed"><strong>${value.toLocaleString()}</strong><div class="exceed-label">超標 ${ratio.toFixed(1)} 倍</div></td>`;}else html+=`<td>${typeof value==="number"?value.toLocaleString():value}</td>`;});row.innerHTML=html;tbody.appendChild(row);});table.appendChild(tbody);tableWrapper.appendChild(table);container.appendChild(tableWrapper);const note=document.createElement("div");note.className="result-note";note.innerHTML=`<span class="exceed-example">超過管制標準</span><span>數值單位：mg/kg（乾基）</span>`;container.appendChild(note);createBoreholeProfile(point,container,standards);
}

function showMonitoringWellDetail(well){showDetailPanel();document.getElementById("point-id").textContent=well.id;document.getElementById("point-type").textContent=well.type;const container=document.getElementById("sample-results");container.innerHTML="";const waterElevation=typeof well.ground_elevation==="number"&&typeof well.water_depth==="number"?well.ground_elevation-well.water_depth:null;const info=document.createElement("div");info.className="well-info-grid";info.innerHTML=`<div class="well-info-item"><span class="well-info-label">地表高程</span><strong>${well.ground_elevation!==undefined?`EL. ${well.ground_elevation.toFixed(2)} m`:"—"}</strong></div><div class="well-info-item"><span class="well-info-label">地下水位深度</span><strong>${well.water_depth!==undefined?`${well.water_depth.toFixed(2)} m`:"—"}</strong></div><div class="well-info-item"><span class="well-info-label">地下水位高程</span><strong>${waterElevation!==null?`EL. ${waterElevation.toFixed(2)} m`:"—"}</strong></div><div class="well-info-item"><span class="well-info-label">篩管深度</span><strong>${well.screen_from!==undefined&&well.screen_to!==undefined?`${formatDepth(well.screen_from)}–${formatDepth(well.screen_to)} m`:"—"}</strong></div>`;container.appendChild(info);const title=document.createElement("h3");title.className="groundwater-result-title";title.textContent="地下水分析結果";container.appendChild(title);const tableWrapper=document.createElement("div");tableWrapper.className="table-wrapper";const table=document.createElement("table");table.className="result-table groundwater-result-table";table.innerHTML=`<thead><tr><th>分析項目</th><th>檢測結果</th><th>單位</th></tr></thead><tbody></tbody>`;const tbody=table.querySelector("tbody");Object.entries(well.results).forEach(([name,result])=>{const row=document.createElement("tr");row.innerHTML=`<td>${name}</td><td>${typeof result.value==="number"?result.value.toLocaleString():result.value}</td><td>${result.unit}</td>`;tbody.appendChild(row);});tableWrapper.appendChild(table);container.appendChild(tableWrapper);createMonitoringWellProfile(well,container);}

function createBoreholeProfile(point,container,standards){if(!point.geology||point.geology.length===0)return;const section=document.createElement("div");section.className="borehole-section";const title=document.createElement("h3");title.textContent="垂直調查剖面";section.appendChild(title);const maxGeologyDepth=Math.max(...point.geology.map(layer=>layer.to));const maxSampleDepth=point.samples.length>0?Math.max(...point.samples.map(sample=>sample.depth_to)):0;const maxDepth=Math.max(maxGeologyDepth,maxSampleDepth);const pixelsPerMeter=95;const profileHeight=maxDepth*pixelsPerMeter;const profile=document.createElement("div");profile.className="borehole-profile";profile.style.height=`${profileHeight}px`;const depthScale=document.createElement("div");depthScale.className="depth-scale";for(let depth=0;depth<=maxDepth+0.001;depth+=0.5){const tick=document.createElement("div");tick.className="depth-tick";tick.style.top=`${depth*pixelsPerMeter}px`;tick.innerHTML=`<span>${depth===0?"0 m":`${depth.toFixed(1)} m`}</span>`;depthScale.appendChild(tick);}profile.appendChild(depthScale);const geologyColumn=document.createElement("div");geologyColumn.className="geology-column";point.geology.forEach(layer=>{const block=document.createElement("div");block.className="geology-layer";block.style.top=`${layer.from*pixelsPerMeter}px`;block.style.height=`${(layer.to-layer.from)*pixelsPerMeter}px`;block.innerHTML=`<span class="geology-name">${layer.material}</span><span class="geology-depth">${formatDepth(layer.from)}–${formatDepth(layer.to)} m</span>`;geologyColumn.appendChild(block);});profile.appendChild(geologyColumn);const sampleColumn=document.createElement("div");sampleColumn.className="sample-column";point.samples.forEach(sample=>{const block=document.createElement("div");const isExceed=Object.entries(sample.results).some(([name,result])=>standards[name]!==undefined&&typeof result.value==="number"&&result.value>standards[name]);block.className=`sample-depth-block${isExceed?" sample-exceed":""}`;block.style.top=`${sample.depth_from*pixelsPerMeter}px`;block.style.height=`${(sample.depth_to-sample.depth_from)*pixelsPerMeter}px`;const tph=sample.results["TPH"]?.value;block.innerHTML=`<div class="sample-name">${point.id}(${formatDepth(sample.depth_from)}–${formatDepth(sample.depth_to)})</div><div class="sample-concentration">${tph!==undefined?`TPH ${tph.toLocaleString()} mg/kg`:""}${isExceed?'<span class="profile-warning">超標</span>':""}</div>`;sampleColumn.appendChild(block);});profile.appendChild(sampleColumn);section.appendChild(profile);const legend=document.createElement("div");legend.className="profile-legend";legend.innerHTML=`<span>左：地層</span><span>右：採樣深度</span><span class="profile-exceed-legend">紅色＝任一項目超標</span>`;section.appendChild(legend);container.appendChild(section);}

function createMonitoringWellProfile(well,container){const section=document.createElement("div");section.className="well-profile-section";const title=document.createElement("h3");title.textContent="監測井垂直構造";section.appendChild(title);const maxDepth=Math.max(well.screen_to??0,(well.water_depth??0)+1,8);const pixelsPerMeter=70;const profileHeight=maxDepth*pixelsPerMeter;const profile=document.createElement("div");profile.className="well-profile";profile.style.height=`${profileHeight}px`;for(let depth=0;depth<=maxDepth+0.001;depth+=1){const line=document.createElement("div");line.className="well-depth-line";line.style.top=`${depth*pixelsPerMeter}px`;line.innerHTML=`<span>${depth} m</span>`;profile.appendChild(line);}const casing=document.createElement("div");casing.className="well-casing";casing.style.top="0px";casing.style.height=`${(well.screen_from??0)*pixelsPerMeter}px`;profile.appendChild(casing);const screen=document.createElement("div");screen.className="well-screen";screen.style.top=`${(well.screen_from??0)*pixelsPerMeter}px`;screen.style.height=`${((well.screen_to??0)-(well.screen_from??0))*pixelsPerMeter}px`;screen.innerHTML=`<span>篩管 ${formatDepth(well.screen_from)}–${formatDepth(well.screen_to)} m</span>`;profile.appendChild(screen);if(well.water_depth!==undefined){const water=document.createElement("div");water.className="groundwater-level";water.style.top=`${well.water_depth*pixelsPerMeter}px`;water.innerHTML=`<span>地下水位 ${well.water_depth.toFixed(2)} m</span>`;profile.appendChild(water);}const bottom=document.createElement("div");bottom.className="well-bottom";bottom.style.top=`${(well.screen_to??maxDepth)*pixelsPerMeter}px`;bottom.innerHTML="<span>井底</span>";profile.appendChild(bottom);section.appendChild(profile);container.appendChild(section);}

function showDetailPanel(){document.getElementById("empty-state").classList.add("hidden");document.getElementById("point-detail").classList.remove("hidden");}
function formatDepth(value){if(typeof value!=="number")return value;return Number.isInteger(value)?value.toFixed(1):String(value);}
