// Excel 匯入 v4：支援 TWD97 / TM2 zone 121（EPSG:3826）與新版中文範例欄位。
let importedWorkbookData=null,importedLayerGroup=null;const originalMapLayers=[];
const excelFileInput=document.getElementById('excel-file'),excelPreviewButton=document.getElementById('excel-preview-button'),excelApplyButton=document.getElementById('excel-apply-button'),excelFileName=document.getElementById('excel-file-name'),excelStatus=document.getElementById('excel-import-status');
map.eachLayer(layer=>{if(!(layer instanceof L.TileLayer))originalMapLayers.push(layer);});
function setExcelStatus(message,type=''){excelStatus.textContent=message;excelStatus.className=`excel-import-status ${type}`.trim();}
function sheetRows(workbook,name){const sheet=workbook.Sheets[name];if(!sheet)return[];return XLSX.utils.sheet_to_json(sheet,{defval:null});}
function numberOrNull(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null;}
function val(row,...keys){for(const k of keys)if(row[k]!==undefined&&row[k]!==null&&row[k]!=='')return row[k];return null;}
function dateText(v){if(v===null||v===undefined)return'';if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);if(d)return`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`;}return String(v).slice(0,10);}
function dynamicResults(row,excluded,defaultUnit){const results={};Object.keys(row).forEach(name=>{if(excluded.includes(name))return;const value=numberOrNull(row[name]);if(value!==null){let analyte=name.replace(/_mgkg$|_mgL$/i,'');results[analyte]={value,unit:/_mgL$/i.test(name)?'mg/L':(/_mgkg$/i.test(name)?'mg/kg':(row.Unit||defaultUnit))};}});return results;}
// EPSG:3826 TWD97 / TM2 zone 121 -> WGS84 latitude/longitude
function twd97ToWgs84(x,y){const a=6378137.0,b=6356752.314245,k0=0.9999,dx=250000,lon0=121*Math.PI/180;const e=Math.sqrt(1-(b*b)/(a*a)),e1=(1-Math.sqrt(1-e*e))/(1+Math.sqrt(1-e*e));x-=dx;const M=y/k0,mu=M/(a*(1-e*e/4-3*Math.pow(e,4)/64-5*Math.pow(e,6)/256));const j1=3*e1/2-27*Math.pow(e1,3)/32,j2=21*e1*e1/16-55*Math.pow(e1,4)/32,j3=151*Math.pow(e1,3)/96,j4=1097*Math.pow(e1,4)/512;const fp=mu+j1*Math.sin(2*mu)+j2*Math.sin(4*mu)+j3*Math.sin(6*mu)+j4*Math.sin(8*mu),e2=e*e/(1-e*e),C1=e2*Math.pow(Math.cos(fp),2),T1=Math.pow(Math.tan(fp),2),R1=a*(1-e*e)/Math.pow(1-e*e*Math.pow(Math.sin(fp),2),1.5),N1=a/Math.sqrt(1-e*e*Math.pow(Math.sin(fp),2)),D=x/(N1*k0);const Q1=N1*Math.tan(fp)/R1,Q2=D*D/2,Q3=(5+3*T1+10*C1-4*C1*C1-9*e2)*Math.pow(D,4)/24,Q4=(61+90*T1+298*C1+45*T1*T1-252*e2-3*C1*C1)*Math.pow(D,6)/720;const lat=fp-Q1*(Q2-Q3+Q4),Q5=D-(1+2*T1+C1)*Math.pow(D,3)/6+(5-2*C1+28*T1-3*C1*C1+8*e2+24*T1*T1)*Math.pow(D,5)/120,lon=lon0+Q5/Math.cos(fp);return{latitude:lat*180/Math.PI,longitude:lon*180/Math.PI};}
function pointCoords(row){const x=numberOrNull(val(row,'TWD97_X','X','Easting')),y=numberOrNull(val(row,'TWD97_Y','Y','Northing'));if(x!==null&&y!==null)return twd97ToWgs84(x,y);const latitude=numberOrNull(val(row,'Latitude','緯度')),longitude=numberOrNull(val(row,'Longitude','經度'));return{latitude,longitude};}
function buildImportedData(workbook){
 const siteRows=sheetRows(workbook,'場址資訊');let siteMap={};if(siteRows.length===1&&!siteRows[0]['欄位'])siteMap={site_name:val(siteRows[0],'場址名稱'),project_name:val(siteRows[0],'專案名稱'),description:val(siteRows[0],'場址說明')};else siteMap=Object.fromEntries(siteRows.filter(r=>r['欄位']).map(r=>[r['欄位'],r['值']]));
 const soilPoints=sheetRows(workbook,'土壤點位'),soilSamples=sheetRows(workbook,'土壤樣品'),wells=sheetRows(workbook,'監測井'),gwResults=sheetRows(workbook,'地下水檢測'),monitor=sheetRows(workbook,'水位浮油監測'),geology=sheetRows(workbook,'地層'),standardsRows=sheetRows(workbook,'法規標準');const errors=[];if(!soilPoints.length&&!wells.length)errors.push('至少需要一筆「土壤點位」或「監測井」資料。');
 const sampling_points=soilPoints.map(p=>{const id=String(val(p,'Point_ID','點位編號')||'').trim(),c=pointCoords(p);if(!id||c.latitude===null||c.longitude===null)errors.push('土壤點位缺少點位編號或有效座標。');const samples=soilSamples.filter(s=>String(val(s,'Point_ID','點位編號')||'').trim()===id).map(s=>({sample_id:val(s,'Sample_ID','樣品編號')||'',depth_from:numberOrNull(val(s,'Depth_From_m','深度_from_m')),depth_to:numberOrNull(val(s,'Depth_To_m','深度_to_m')),results:dynamicResults(s,['Point_ID','點位編號','Sample_ID','樣品編號','Depth_From_m','深度_from_m','Depth_To_m','深度_to_m','Unit','Note'],'mg/kg')}));const pointGeology=geology.filter(g=>String(val(g,'Point_ID','點位編號')||'').trim()===id).map(g=>({from:numberOrNull(val(g,'Depth_From_m','深度_from_m')),to:numberOrNull(val(g,'Depth_To_m','深度_to_m')),material:val(g,'Geology','材質')||'未命名地層',description:val(g,'Description','描述')||'',note:val(g,'Note','備註')||''})).filter(g=>g.from!==null&&g.to!==null&&g.to>g.from);return{id,latitude:c.latitude,longitude:c.longitude,twd97_x:numberOrNull(val(p,'TWD97_X')),twd97_y:numberOrNull(val(p,'TWD97_Y')),ground_elevation:numberOrNull(val(p,'Ground_EL_m','地表高程_EL_m')),type:val(p,'Type','類型')||'土壤調查點',note:val(p,'Note','備註')||'',samples,geology:pointGeology};}).filter(p=>p.id&&p.latitude!==null&&p.longitude!==null);
 const monitoring_wells=wells.map(w=>{const id=String(val(w,'Well_ID','井號')||'').trim(),c=pointCoords(w);if(!id||c.latitude===null||c.longitude===null)errors.push('監測井缺少井號或有效座標。');const gwRows=gwResults.filter(r=>String(val(r,'Well_ID','井號')||'').trim()===id),latestGW=gwRows.slice(-1)[0],results=latestGW?dynamicResults(latestGW,['Well_ID','井號','Sample_Date','採樣日期','Sample_ID','樣品編號','Unit','Note'],'mg/L'):{};const historyRows=monitor.filter(r=>String(val(r,'Well_ID','井號')||'').trim()===id),latest=historyRows.slice(-1)[0],waterDepth=numberOrNull(val(latest||{},'Water_Depth_m','地下水位深度_m'))??numberOrNull(val(w,'Water_Depth_m','地下水位深度_m')),oilDepth=numberOrNull(val(latest||{},'LNAPL_Depth_m','油面深度_m')),oilThickness=numberOrNull(val(latest||{},'Apparent_LNAPL_Thickness_m','表觀浮油厚度_m')),hasOil=String(val(w,'Has_LNAPL','具有浮油')||'').toUpperCase()==='Y'||(oilThickness!==null&&oilThickness>0);return{id,latitude:c.latitude,longitude:c.longitude,twd97_x:numberOrNull(val(w,'TWD97_X')),twd97_y:numberOrNull(val(w,'TWD97_Y')),type:'地下水監測井',ground_elevation:numberOrNull(val(w,'Ground_EL_m','地表高程_EL_m')),well_depth:numberOrNull(val(w,'Well_Depth_m','井深_m')),screen_from:numberOrNull(val(w,'Screen_From_m','篩管_from_m')),screen_to:numberOrNull(val(w,'Screen_To_m','篩管_to_m')),water_depth:waterDepth,has_lnapl:hasOil,lnapl_depth:oilDepth,lnapl_thickness:oilThickness,results,groundwater_history:gwRows.map(r=>({date:dateText(val(r,'Sample_Date','採樣日期')),results:dynamicResults(r,['Well_ID','井號','Sample_Date','採樣日期','Sample_ID','樣品編號','Unit','Note'],'mg/L')})),history:historyRows.map(r=>({date:dateText(val(r,'Measure_Date','日期')),water_depth:numberOrNull(val(r,'Water_Depth_m','地下水位深度_m')),lnapl_depth:numberOrNull(val(r,'LNAPL_Depth_m','油面深度_m')),lnapl_thickness:numberOrNull(val(r,'Apparent_LNAPL_Thickness_m','表觀浮油厚度_m'))||0}))};}).filter(w=>w.id&&w.latitude!==null&&w.longitude!==null);
 const standards={};standardsRows.forEach(r=>{const v=numberOrNull(val(r,'Standard_Value','標準值'));if(v!==null){const media=val(r,'Media','介質')||'土壤',analyte=val(r,'Analyte','項目');standards[`${media}:${analyte}`]={value:v,unit:val(r,'Unit','單位'),source:val(r,'Source_Note','備註')};}});return{site:{name:siteMap.site_name||'匯入場址',project:siteMap.project_name||'Excel 匯入資料',description:siteMap.description||''},sampling_points,monitoring_wells,standards,errors,counts:{soilSamples:soilSamples.length,groundwaterResults:gwResults.length,monitoring:monitor.length,geology:geology.length}};
}
excelFileInput.addEventListener('change',async event=>{importedWorkbookData=null;excelApplyButton.disabled=true;const file=event.target.files[0];if(!file){excelPreviewButton.disabled=true;excelFileName.textContent='尚未選擇檔案';return;}excelFileName.textContent=file.name;try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});importedWorkbookData=buildImportedData(workbook);excelPreviewButton.disabled=false;setExcelStatus('Excel 已讀取。支援 TWD97 / TM2 zone 121 座標，按「檢查資料」查看摘要。');}catch(error){console.error(error);excelPreviewButton.disabled=true;setExcelStatus(`Excel 讀取失敗：${error.message}`,'error');}});
excelPreviewButton.addEventListener('click',()=>{if(!importedWorkbookData)return;const d=importedWorkbookData;if(d.errors.length){excelApplyButton.disabled=true;setExcelStatus(`資料檢查未通過：${[...new Set(d.errors)].join('；')}`,'error');return;}excelApplyButton.disabled=false;setExcelStatus(`檢查完成｜土壤點 ${d.sampling_points.length}｜土壤樣品 ${d.counts.soilSamples}｜監測井 ${d.monitoring_wells.length}｜地下水檢測 ${d.counts.groundwaterResults}｜水位/浮油 ${d.counts.monitoring}｜地層 ${d.counts.geology}。`,'success');});
function clearOldDataLayers(){originalMapLayers.forEach(layer=>{if(map.hasLayer(layer))map.removeLayer(layer);});if(importedLayerGroup&&map.hasLayer(importedLayerGroup))map.removeLayer(importedLayerGroup);const remove=[];map.eachLayer(layer=>{if(layer instanceof L.Marker)remove.push(layer);});remove.forEach(layer=>map.removeLayer(layer));}
function applyImportedData(data){clearOldDataLayers();importedLayerGroup=L.layerGroup().addTo(map);const coords=[];data.sampling_points.forEach(point=>{const c=[point.latitude,point.longitude];coords.push(c);const marker=L.marker(c).addTo(importedLayerGroup).bindTooltip(point.id,{permanent:true,direction:'top'});marker.on('click',()=>showSoilPointDetail(point));});data.monitoring_wells.forEach(well=>{const c=[well.latitude,well.longitude];coords.push(c);const marker=L.marker(c,{icon:monitoringWellIcon}).addTo(importedLayerGroup).bindTooltip(well.id,{permanent:true,direction:'top',className:'mw-tooltip'});marker.on('click',()=>showMonitoringWellDetail(well));if(well.has_lnapl)L.marker(c,{icon:L.divIcon({className:'lnapl-map-marker',html:'<div class="lnapl-map-icon">◆</div>',iconSize:[18,18],iconAnchor:[-10,18]}),interactive:false}).addTo(importedLayerGroup);});document.getElementById('site-description').textContent=`${data.site.name}｜${data.site.project}`;document.getElementById('point-detail').classList.add('hidden');document.getElementById('empty-state').classList.remove('hidden');if(coords.length)map.fitBounds(coords,{padding:[50,50],maxZoom:18});}
excelApplyButton.addEventListener('click',()=>{if(!importedWorkbookData||importedWorkbookData.errors.length)return;applyImportedData(importedWorkbookData);setExcelStatus(`已切換為 Excel 資料｜${importedWorkbookData.site.name}。TWD97 座標已自動轉換供 Leaflet 顯示；重新整理頁面會回到 GitHub Demo。`,'success');});