// Groundwater / LNAPL UI — single source of truth.
// Data contract: well geometry comes from 地下水點位; time series comes from 浮油數據 via well.history.
(function(){
 const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
 const f=(v,d=2)=>n(v)===null?'—':n(v).toFixed(d);
 function rows(well){return (well.history||[]).map((r,i)=>{const water=n(r.water_depth),th=n(r.lnapl_thickness),rawOil=n(r.lnapl_depth),oil=rawOil!==null?rawOil:(water!==null&&th!==null?water-th:null);return{...r,_i:i,water_depth:water,lnapl_depth:oil,lnapl_thickness:th!==null?th:(water!==null&&oil!==null?Math.max(0,water-oil):0)}}).filter(r=>r.water_depth!==null&&r.lnapl_depth!==null)}
 function tabs(container){container.innerHTML='';const defs=[['overview','概況'],['results','分析結果'],['profile','垂直剖面'],['history','歷次資料']],nav=document.createElement('div'),panels={};nav.className='detail-tabs';defs.forEach(([id,label],i)=>{const b=document.createElement('button');b.type='button';b.className='detail-tab '+(i?'':'active');b.textContent=label;b.onclick=()=>{nav.querySelectorAll('.detail-tab').forEach(x=>x.classList.toggle('active',x===b));Object.entries(panels).forEach(([k,p])=>p.classList.toggle('active',k===id))};nav.appendChild(b)});container.appendChild(nav);defs.forEach(([id],i)=>{const p=document.createElement('div');p.className='detail-tab-panel '+(i?'':'active');container.appendChild(p);panels[id]=p});return panels}
 function overview(well,p){const el=(label,value)=>`<div class="well-info-item"><span class="well-info-label">${label}</span><strong>${value}</strong></div>`;const elev=n(well.ground_elevation),water=n(well.water_depth);p.innerHTML='<div class="well-info-grid">'+el('井頂高程',elev===null?'—':`EL. ${elev.toFixed(2)} m`)+el('井深',f(well.well_depth)+' m')+el('地下水位深度',f(water,3)+' m')+el('地下水位高程',elev!==null&&water!==null?`EL. ${(elev-water).toFixed(2)} m`:'—')+el('篩管深度',n(well.screen_from)!==null&&n(well.screen_to)!==null?`${f(well.screen_from)}–${f(well.screen_to)} m`:'—')+'</div>'}
 function results(well,p){p.innerHTML='<h3>地下水分析結果</h3>';const wrap=document.createElement('div');wrap.className='table-wrapper';const table=document.createElement('table');table.className='result-table groundwater-result-table';table.innerHTML='<thead><tr><th>分析項目</th><th>檢測結果</th><th>單位</th></tr></thead><tbody></tbody>';Object.entries(well.results||{}).forEach(([name,r])=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${name}</td><td>${r.value??'—'}</td><td>${r.unit||''}</td>`;table.tBodies[0].appendChild(tr)});wrap.appendChild(table);p.appendChild(wrap)}
 function profile(well,p){const data=rows(well);const section=document.createElement('section');section.className='gw-profile-v2';section.innerHTML='<h3>監測井浮油時序剖面</h3>';p.appendChild(section);if(!data.length){section.insertAdjacentHTML('beforeend','<div class="empty-tab-message">此井目前沒有可繪製的「浮油數據」（需有水位，以及油位或浮油厚度）。</div>');return}
  const depth=Math.max(n(well.well_depth)||0,n(well.screen_to)||0,...data.map(r=>r.water_depth),8)+.25,W=650,H=Math.max(430,Math.min(650,depth*58)),top=24,bottom=22,plotH=H-top-bottom,y=d=>top+d/depth*plotH,wellX=155,wellW=52;
  const box=document.createElement('div');box.className='gw-profile-chart';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.setAttribute('role','img');box.appendChild(svg);
  function S(tag,attrs={},text=''){const x=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>x.setAttribute(k,v));if(text)x.textContent=text;svg.appendChild(x);return x}
  for(let d=0;d<=Math.ceil(depth);d++){S('line',{x1:55,y1:y(d),x2:620,y2:y(d),class:'gw-grid'});S('text',{x:45,y:y(d)+4,'text-anchor':'end',class:'gw-depth-text'},d+' m')}
  S('line',{x1:wellX,y1:y(0),x2:wellX,y2:y(n(well.well_depth)||depth),class:'gw-casing'});S('line',{x1:wellX+wellW,y1:y(0),x2:wellX+wellW,y2:y(n(well.well_depth)||depth),class:'gw-casing'});S('line',{x1:wellX,y1:y(n(well.well_depth)||depth),x2:wellX+wellW,y2:y(n(well.well_depth)||depth),class:'gw-casing'});
  const sf=n(well.screen_from),st=n(well.screen_to);if(sf!==null&&st!==null){S('line',{x1:wellX,y1:y(sf),x2:wellX,y2:y(st),class:'gw-screen'});S('line',{x1:wellX+wellW,y1:y(sf),x2:wellX+wellW,y2:y(st),class:'gw-screen'});S('text',{x:wellX+wellW+22,y:y(sf)+16,class:'gw-screen-text'},`井篩 ${sf.toFixed(2)}–${st.toFixed(2)} m`)}
  const water=S('rect',{x:wellX+4,width:wellW-8,class:'gw-water'}),oil=S('rect',{x:wellX+4,width:wellW-8,class:'gw-oil'}),waterLine=S('line',{x1:wellX-80,x2:wellX+250,class:'gw-water-line'}),oilText=S('text',{x:wellX+wellW+22,class:'gw-oil-text'}),waterText=S('text',{x:wellX+wellW+190,class:'gw-water-text'});
  section.appendChild(box);const controls=document.createElement('div');controls.className='gw-time-controls';controls.innerHTML='<div class="gw-time-head"><strong class="gw-date"></strong><span class="gw-count"></span></div><input class="gw-slider" type="range" min="0" max="'+(data.length-1)+'" step="1" value="'+(data.length-1)+'"><div class="gw-axis"></div><div class="gw-readout"></div>';section.appendChild(controls);const slider=controls.querySelector('.gw-slider'),date=controls.querySelector('.gw-date'),count=controls.querySelector('.gw-count'),axis=controls.querySelector('.gw-axis'),read=controls.querySelector('.gw-readout');
  data.forEach((r,i)=>{const b=document.createElement('button');b.type='button';b.title=r.date||('第 '+(i+1)+' 筆');b.textContent='●';b.onclick=()=>{slider.value=i;draw(i)};axis.appendChild(b)});
  function draw(i){const r=data[i],oy=y(r.lnapl_depth),wy=y(r.water_depth);water.setAttribute('y',wy);water.setAttribute('height',Math.max(0,y(depth)-wy));oil.setAttribute('y',oy);oil.setAttribute('height',Math.max(3,wy-oy));waterLine.setAttribute('y1',wy);waterLine.setAttribute('y2',wy);oilText.setAttribute('y',oy+Math.max(14,(wy-oy)/2+4));oilText.textContent=`浮油 (LNAPL)  ${f(r.lnapl_thickness,3)} m`;waterText.setAttribute('y',wy+4);waterText.textContent=`地下水位 ${f(r.water_depth,3)} m`;date.textContent=r.date||('第 '+(i+1)+' 筆量測');count.textContent=`${i+1} / ${data.length}`;read.textContent=`油位 ${f(r.lnapl_depth,3)} m｜水位 ${f(r.water_depth,3)} m｜浮油厚度 ${f(r.lnapl_thickness,3)} m${r.note?'｜'+r.note:''}`;[...axis.children].forEach((b,j)=>b.classList.toggle('active',j===i))}
  slider.oninput=()=>draw(Number(slider.value));draw(data.length-1)
 }
 function history(well,p){const all=well.history||[];if(!all.length){p.innerHTML='<div class="empty-tab-message">目前沒有浮油數據歷次資料。</div>';return}p.innerHTML='<h3>歷次水位與浮油資料</h3>';const wrap=document.createElement('div');wrap.className='table-wrapper';const table=document.createElement('table');table.className='result-table groundwater-result-table history-table';table.innerHTML='<thead><tr><th>日期</th><th>油位深度 (m, TOC)</th><th>水位深度 (m, TOC)</th><th>浮油厚度 (m)</th><th>備註</th></tr></thead><tbody>'+all.map(r=>`<tr><td>${r.date||'—'}</td><td>${f(r.lnapl_depth,3)}</td><td>${f(r.water_depth,3)}</td><td>${f(r.lnapl_thickness,3)}</td><td>${r.note||''}</td></tr>`).join('')+'</tbody>';wrap.appendChild(table);p.appendChild(wrap)}
 function show(well){showDetailPanel();document.getElementById('point-id').textContent=well.id;document.getElementById('point-type').textContent=well.type||'地下水監測井';const p=tabs(document.getElementById('sample-results'));overview(well,p.overview);results(well,p.results);profile(well,p.profile);history(well,p.history)}
 window.GroundwaterUI={show,profile,history,rows};window.showMonitoringWellDetail=show;
})();