// Groundwater / LNAPL UI — single source of truth.
// Data contract: well geometry comes from 地下水點位; time series comes from 浮油數據 via well.history.
(function(){
 const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
 const f=(v,d=2)=>n(v)===null?'—':n(v).toFixed(d);
 function rows(well){return (well.history||[]).map((r,i)=>{const water=n(r.water_depth),th=n(r.lnapl_thickness),rawOil=n(r.lnapl_depth),oil=rawOil!==null?rawOil:(water!==null&&th!==null?water-th:null);return{...r,_i:i,water_depth:water,lnapl_depth:oil,lnapl_thickness:th!==null?th:(water!==null&&oil!==null?Math.max(0,water-oil):0)}}).filter(r=>r.water_depth!==null&&r.lnapl_depth!==null)}
 function tabs(container){container.innerHTML='';const defs=[['overview','概況'],['results','分析結果'],['profile','垂直剖面'],['allwells','浮油井總覽'],['history','歷次資料']],nav=document.createElement('div'),panels={};nav.className='detail-tabs';defs.forEach(([id,label],i)=>{const b=document.createElement('button');b.type='button';b.className='detail-tab '+(i?'':'active');b.textContent=label;b.onclick=()=>{nav.querySelectorAll('.detail-tab').forEach(x=>x.classList.toggle('active',x===b));Object.entries(panels).forEach(([k,p])=>p.classList.toggle('active',k===id))};nav.appendChild(b)});container.appendChild(nav);defs.forEach(([id],i)=>{const p=document.createElement('div');p.className='detail-tab-panel '+(i?'':'active');container.appendChild(p);panels[id]=p});return panels}
 function overview(well,p){const el=(label,value)=>`<div class="well-info-item"><span class="well-info-label">${label}</span><strong>${value}</strong></div>`;const elev=n(well.ground_elevation),water=n(well.water_depth);p.innerHTML='<div class="well-info-grid">'+el('井頂高程',elev===null?'—':`EL. ${elev.toFixed(2)} m`)+el('井深',f(well.well_depth)+' m')+el('地下水位深度',f(water,3)+' m')+el('地下水位高程',elev!==null&&water!==null?`EL. ${(elev-water).toFixed(2)} m`:'—')+el('篩管深度',n(well.screen_from)!==null&&n(well.screen_to)!==null?`${f(well.screen_from)}–${f(well.screen_to)} m`:'—')+'</div>'}
 function results(well,p){p.innerHTML='<h3>地下水分析結果</h3>';const wrap=document.createElement('div');wrap.className='table-wrapper';const table=document.createElement('table');table.className='result-table groundwater-result-table';table.innerHTML='<thead><tr><th>分析項目</th><th>檢測結果</th><th>單位</th></tr></thead><tbody></tbody>';Object.entries(well.results||{}).forEach(([name,r])=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${name}</td><td>${r.value??'—'}</td><td>${r.unit||''}</td>`;table.tBodies[0].appendChild(tr)});wrap.appendChild(table);p.appendChild(wrap)}
 function profile(well,p){const data=rows(well);const section=document.createElement('section');section.className='gw-profile-v3';section.innerHTML='<h3>監測井浮油時序剖面</h3>';p.appendChild(section);if(!data.length){section.insertAdjacentHTML('beforeend','<div class="empty-tab-message">此井目前沒有可繪製的「浮油數據」。</div>');return}
  const layout=document.createElement('div');layout.className='gw-profile-layout';const chart=document.createElement('div');chart.className='gw-profile-chart-v3';const side=document.createElement('aside');side.className='gw-profile-side';layout.append(chart,side);section.appendChild(layout);
  const depth=8,W=560,H=410,top=34,bottom=20,plotH=H-top-bottom,y=d=>top+(Math.max(0,Math.min(depth,d))/depth)*plotH,wellX=142,wellW=58,wellBottom=y(n(well.well_depth)||depth);
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);chart.appendChild(svg);function S(tag,attrs={},text=''){const x=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>x.setAttribute(k,v));if(text)x.textContent=text;svg.appendChild(x);return x}
  S('text',{x:36,y:18,class:'gw-axis-title'},'深度 (m, TOC)');for(let d=0;d<=Math.ceil(depth);d++){S('line',{x1:54,y1:y(d),x2:530,y2:y(d),class:'gw-grid'});S('text',{x:45,y:y(d)+4,'text-anchor':'end',class:'gw-depth-text'},String(d))}
  S('line',{x1:wellX,y1:y(0),x2:wellX,y2:wellBottom,class:'gw-casing'});S('line',{x1:wellX+wellW,y1:y(0),x2:wellX+wellW,y2:wellBottom,class:'gw-casing'});S('line',{x1:wellX,y1:wellBottom,x2:wellX+wellW,y2:wellBottom,class:'gw-casing'});
  const sf=n(well.screen_from),st=n(well.screen_to);if(sf!==null&&st!==null){for(let d=sf;d<=st+.001;d+=.22)S('line',{x1:wellX+4,y1:y(d),x2:wellX+wellW-4,y2:y(d),class:'gw-screen-hatch'})}
  const water=S('rect',{x:wellX+5,width:wellW-10,class:'gw-water'}),oil=S('rect',{x:wellX+5,width:wellW-10,class:'gw-oil'}),oilLine=S('line',{x1:wellX+wellW-2,x2:wellX+310,class:'gw-oil-line'}),waterLine=S('line',{x1:wellX-4,x2:wellX+310,class:'gw-water-line'}),oilText=S('text',{x:wellX+wellW+22,class:'gw-oil-text'}),waterText=S('text',{x:wellX+wellW+225,class:'gw-water-text'}),bottomText=S('text',{x:wellX+wellW+22,y:wellBottom+4,class:'gw-bottom-text'},`井底 ${f(well.well_depth,2)} m`);
  side.innerHTML='<div class="gw-side-label">時間</div><div class="gw-side-head"><strong class="gw-date"></strong><span class="gw-count"></span></div><div class="gw-slider-row"><button class="gw-prev" type="button">‹</button><input class="gw-slider" type="range" min="0" max="'+(data.length-1)+'" step="1" value="'+(data.length-1)+'"><button class="gw-next" type="button">›</button></div><div class="gw-axis"></div><div class="gw-metrics"><div><span>油位 (m, TOC)</span><strong class="m-oil"></strong></div><div><span>水位 (m, TOC)</span><strong class="m-water"></strong></div><div><span>浮油厚度 (m)</span><strong class="m-thick"></strong></div><hr><div><span>井頂高程 (m, MSL)</span><strong class="m-el"></strong></div><div><span>井底深度 (m, TOC)</span><strong class="m-depth"></strong></div></div>';
  const slider=side.querySelector('.gw-slider'),date=side.querySelector('.gw-date'),count=side.querySelector('.gw-count'),axis=side.querySelector('.gw-axis');data.forEach((r,i)=>{const b=document.createElement('button');b.type='button';b.textContent='●';b.title=r.date||'';b.onclick=()=>{slider.value=i;draw(i)};axis.appendChild(b)});
  function draw(i){const r=data[i],oy=y(r.lnapl_depth),wy=y(r.water_depth),waterBottom=Math.max(wy,wellBottom);water.setAttribute('y',wy);water.setAttribute('height',Math.max(0,waterBottom-wy));oil.setAttribute('y',oy);oil.setAttribute('height',Math.max(3,wy-oy));oilLine.setAttribute('y1',oy);oilLine.setAttribute('y2',oy);waterLine.setAttribute('y1',wy);waterLine.setAttribute('y2',wy);oilText.setAttribute('y',oy-7);oilText.textContent=`浮油厚度  ${f(r.lnapl_thickness,3)} m`;waterText.setAttribute('y',wy+4);waterText.textContent=`地下水位 ${f(r.water_depth,3)} m`;date.textContent=r.date||`第 ${i+1} 筆`;count.textContent=`第 ${i+1} / ${data.length} 筆`;side.querySelector('.m-oil').textContent=f(r.lnapl_depth,3);side.querySelector('.m-water').textContent=f(r.water_depth,3);side.querySelector('.m-thick').textContent=f(r.lnapl_thickness,3);side.querySelector('.m-el').textContent=f(well.ground_elevation,3);side.querySelector('.m-depth').textContent=f(well.well_depth,2);[...axis.children].forEach((b,j)=>b.classList.toggle('active',j===i))}
  slider.oninput=()=>draw(Number(slider.value));side.querySelector('.gw-prev').onclick=()=>{slider.value=Math.max(0,Number(slider.value)-1);draw(Number(slider.value))};side.querySelector('.gw-next').onclick=()=>{slider.value=Math.min(data.length-1,Number(slider.value)+1);draw(Number(slider.value))};draw(data.length-1)
 }
 function allWells(p){const wells=(window.currentImportedData?.monitoring_wells||[]).filter(w=>rows(w).some(r=>r.lnapl_thickness>0));p.innerHTML='<h3>浮油井時序總覽</h3>';if(!wells.length){p.insertAdjacentHTML('beforeend','<div class="empty-tab-message">目前沒有浮油井資料。</div>');return}const times=[...new Set(wells.flatMap(w=>rows(w).map(r=>r.date).filter(Boolean)))].sort((a,b)=>new Date(a)-new Date(b)),ctl=document.createElement('div'),grid=document.createElement('div');ctl.className='allwells-control';ctl.innerHTML='<strong class="all-date"></strong><input type="range" min="0" max="'+(times.length-1)+'" value="'+(times.length-1)+'" step="1"><span class="all-count"></span>';grid.className='allwells-grid';p.append(ctl,grid);const slider=ctl.querySelector('input');function render(ix){const time=times[ix]||'';ctl.querySelector('.all-date').textContent=time;ctl.querySelector('.all-count').textContent=(ix+1)+' / '+times.length;grid.innerHTML='';wells.forEach(w=>{const target=new Date(time).getTime(),candidates=rows(w).map(x=>({x,dt:Math.abs(new Date(x.date).getTime()-target)})).filter(z=>Number.isFinite(z.dt)&&z.dt<=10*24*60*60*1000).sort((a,b)=>a.dt-b.dt),r=candidates[0]?.x||null,card=document.createElement('div');card.className='allwell-card'+(r?'':' no-data');card.innerHTML='<h4>'+w.id+'</h4>';const depth=8,H=250,top=18,bottom=12,y=d=>top+Math.max(0,Math.min(depth,d))/depth*(H-top-bottom),wx=58,ww=42,svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 220 '+H);function S(tag,a,txt){const z=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(a||{}).forEach(([k,v])=>z.setAttribute(k,v));if(txt)z.textContent=txt;svg.appendChild(z);return z}for(let d=0;d<=8;d+=2){S('line',{x1:28,y1:y(d),x2:205,y2:y(d),class:'gw-grid'});S('text',{x:23,y:y(d)+4,'text-anchor':'end',class:'gw-depth-text'},String(d))}const wb=Math.min(y(n(w.well_depth)||8),y(8));S('line',{x1:wx,y1:y(0),x2:wx,y2:wb,class:'gw-casing'});S('line',{x1:wx+ww,y1:y(0),x2:wx+ww,y2:wb,class:'gw-casing'});S('line',{x1:wx,y1:wb,x2:wx+ww,y2:wb,class:'gw-casing'});const sf=n(w.screen_from),st=n(w.screen_to);if(sf!==null&&st!==null)for(let d=sf;d<=Math.min(st,8);d+=.28)S('line',{x1:wx+4,y1:y(d),x2:wx+ww-4,y2:y(d),class:'gw-screen-hatch'});if(r){const oy=y(r.lnapl_depth),wy=y(r.water_depth);S('rect',{x:wx+5,y:wy,width:ww-10,height:Math.max(0,wb-wy),class:'gw-water'});S('rect',{x:wx+5,y:oy,width:ww-10,height:Math.max(3,wy-oy),class:'gw-oil'});S('text',{x:112,y:oy+4,class:'gw-oil-text'},'油厚 '+f(r.lnapl_thickness,3)+' m')}else S('text',{x:112,y:125,'text-anchor':'middle',class:'allwell-nodata'},'±10天內無數據');card.appendChild(svg);const foot=document.createElement('div');foot.className='allwell-foot';foot.textContent=r?'油位 '+f(r.lnapl_depth,3)+'｜水位 '+f(r.water_depth,3):'—';card.appendChild(foot);grid.appendChild(card)})}slider.oninput=()=>render(Number(slider.value));render(Number(slider.value))}

 function history(well,p){const all=well.history||[];if(!all.length){p.innerHTML='<div class="empty-tab-message">目前沒有浮油數據歷次資料。</div>';return}p.innerHTML='<h3>歷次水位與浮油資料</h3>';const wrap=document.createElement('div');wrap.className='table-wrapper';const table=document.createElement('table');table.className='result-table groundwater-result-table history-table';table.innerHTML='<thead><tr><th>序號</th><th>Date & Time</th><th>油位 (m, TOC)</th><th>水位 (m, TOC)</th><th>浮油厚度 (m)</th><th>備註</th></tr></thead><tbody>'+all.map((r,i)=>`<tr><td>${i+1}</td><td>${r.date||'—'}</td><td>${f(r.lnapl_depth,3)}</td><td>${f(r.water_depth,3)}</td><td>${f(r.lnapl_thickness,3)}</td><td>${r.note||''}</td></tr>`).join('')+'</tbody>';wrap.appendChild(table);p.appendChild(wrap)}
 function show(well){showDetailPanel();document.getElementById('point-id').textContent=well.id;document.getElementById('point-type').textContent=well.type||'地下水監測井';const p=tabs(document.getElementById('sample-results'));overview(well,p.overview);results(well,p.results);profile(well,p.profile);allWells(p.allwells);history(well,p.history)}
 window.GroundwaterUI={show,profile,allWells,history,rows};window.showMonitoringWellDetail=show;
})();