// 專業化 UI：多軌垂直調查剖面
(function(){
 const isMobile=()=>window.matchMedia('(max-width:600px)').matches;
 const profilePrefs=window.profilePrefs||(window.profilePrefs={selected:['kit','interp'],vscale:isMobile()?1.15:.8,wscale:.85,userScaled:false});
 function displayValue(v){if(v===null||v===undefined||v==='')return'—';return typeof v==='number'?v.toLocaleString():String(v)}
 function numericValue(v){if(typeof v==='number')return v;if(typeof v==='string'&&/^\s*[0-9,.]+\s*$/.test(v))return Number(v.replace(/,/g,''));return null}
 function soilTphStandard(s){const c=[s?.['土壤:TPH']?.value,s?.TPH?.value,1000];return c.find(v=>typeof v==='number'&&isFinite(v))||1000}
 function tphLevel(v,standard){const n=numericValue(v);if(n===null)return'';if(n>=standard)return'exceed';if(n>=standard/2)return'warning';return''}
 function pointLabTphLevel(point,standards){const standard=soilTphStandard(standards);let level='normal';(point.samples||[]).forEach(s=>{const current=tphLevel(s.results?.TPH?.value,standard);if(current==='exceed')level='exceed';else if(current==='warning'&&level!=='exceed')level='warning'});return level}
 function soilPinIcon(level){const cls=level==='exceed'?'soil-risk-pin soil-risk-red':level==='warning'?'soil-risk-pin soil-risk-orange':'soil-risk-pin soil-risk-green';return L.divIcon({className:'soil-risk-marker',html:`<span class="${cls}"><i></i></span>`,iconSize:[26,38],iconAnchor:[13,36],tooltipAnchor:[0,-32]})}
 function recolorImportedSoilPins(data){if(typeof importedLayerGroup==='undefined'||!importedLayerGroup)return;const soil=data.sampling_points||[],layers=importedLayerGroup.getLayers().filter(l=>l instanceof L.Marker);soil.forEach((point,i)=>{const marker=layers[i];if(marker)marker.setIcon(soilPinIcon(pointLabTphLevel(point,data.standards||{})))});}
 if(typeof applyImportedData==='function'){const originalApplyImportedData=applyImportedData;applyImportedData=function(data){originalApplyImportedData(data);recolorImportedSoilPins(data)}}
 function addProfileTracks(point,section,profile,standards,maxDepth){
  const old=profile.querySelector('.sample-column');if(old)old.remove();
  const options=[{key:'pid',label:'PID',unit:'ppmV'},{key:'fid',label:'FID',unit:'ppmV'},{key:'kit',label:'TPH Test Kit（柴）',unit:'mg/kg'},{key:'interp',label:'統計推估值（內插採用值）',unit:'mg/kg'}],standard=soilTphStandard(standards);
  const selector=document.createElement('div');selector.className='profile-metric-selector';const vMax=isMobile()?2.0:1.2;selector.innerHTML='<span class="profile-selector-title">加選剖面項目</span>'+options.map(m=>`<label><input type="checkbox" value="${m.key}"${profilePrefs.selected.includes(m.key)?' checked':''}>${m.label}</label>`).join('')+`<span class="profile-size-controls"><label>垂直比例 <input class="profile-vscale" type="range" min="0.4" max="${vMax}" step="0.1" value="${profilePrefs.vscale}"></label><label>欄寬 <input class="profile-wscale" type="range" min="0.5" max="1.8" step="0.1" value="${profilePrefs.wscale}"></label></span>`;
  const title=section.querySelector('h3,h2');if(title){let row=document.createElement('div');row.className='profile-heading-row';title.parentNode.insertBefore(row,title);row.appendChild(title);row.appendChild(selector)}else section.insertBefore(selector,profile);
  const lab=document.createElement('div');lab.className='profile-data-track profile-lab-track';profile.appendChild(lab);
  function block(track,from,to,value,unit,level=''){if(value===null||value===undefined||value==='')return;const e=document.createElement('div');e.className='profile-track-block'+(level==='exceed'?' profile-track-exceed':level==='warning'?' profile-track-warning':'');e.dataset.from=from;e.dataset.to=to;e.innerHTML=`<strong>${displayValue(value)}${unit?' <small>'+unit+'</small>':''}</strong>${level==='exceed'?'<span class="profile-exceed-text">超標</span>':level==='warning'?'<span class="profile-warning-text">≥ 1/2 管制標準</span>':''}`;track.appendChild(e)}
  (point.samples||[]).forEach(s=>{const v=s.results?.TPH?.value;block(lab,+s.depth_from,+s.depth_to,v,'mg/kg',tphLevel(v,standard))});const h=document.createElement('div');h.className='profile-track-header';h.textContent='Lab TPH';lab.appendChild(h);
  const originalGeology=[...(point.geology||[])];
  function requiredPpm(basePpm){let ppm=basePpm;profile.querySelectorAll('.profile-track-block').forEach(e=>{const span=(+e.dataset.to)-(+e.dataset.from);if(span>0){const needed=Math.max(42,e.scrollHeight+8);ppm=Math.max(ppm,needed/span)}});profile.querySelectorAll('.geology-layer').forEach((e,i)=>{const g=originalGeology[i],span=g?(+g.to-+g.from):0;if(span>0)ppm=Math.max(ppm,(Math.max(42,e.scrollHeight+8))/span)});return ppm}
  function applyScale(autoFit=false){const vs=+selector.querySelector('.profile-vscale').value||.8,ws=+selector.querySelector('.profile-wscale').value||.85;const basePpm=95*vs;const ppm=autoFit?requiredPpm(basePpm):basePpm;profile.style.height=Math.max(80,maxDepth*ppm)+'px';profile.style.setProperty('--width-scale',ws);profile.querySelectorAll('[data-from][data-to]').forEach(e=>{e.style.top=(+e.dataset.from*ppm)+'px';e.style.height=((+e.dataset.to-+e.dataset.from)*ppm)+'px'});profile.querySelectorAll('.geology-layer').forEach((e,i)=>{const g=originalGeology[i];if(g){e.style.top=(+g.from*ppm)+'px';e.style.height=((+g.to-+g.from)*ppm)+'px'}});profile.querySelectorAll('.depth-tick').forEach(e=>{const txt=e.textContent||'',m=txt.match(/([0-9.]+)\s*m/);if(m)e.style.top=(+m[1]*ppm)+'px'});profilePrefs.vscale=vs;profilePrefs.wscale=ws}
  function render(autoFit=!profilePrefs.userScaled){profile.querySelectorAll('.profile-optional-track').forEach(e=>e.remove());const selected=[...selector.querySelectorAll('input[type=checkbox]:checked')].map(e=>e.value);profilePrefs.selected=[...selected];profile.style.setProperty('--optional-count',selected.length);selected.forEach((key,i)=>{const m=options.find(x=>x.key===key),track=document.createElement('div');track.className='profile-data-track profile-optional-track';track.style.setProperty('--track-index',i);const hh=document.createElement('div');hh.className='profile-track-header';hh.textContent=m.label;track.appendChild(hh);(point.field_screening||[]).forEach(r=>{const v=key==='pid'?r.pid:key==='fid'?r.fid:key==='kit'?r.tph_test_kit_diesel:r.interpolation_value;const level=(key==='kit'||key==='interp')?tphLevel(v,standard):'';block(track,+r.depth_from,+r.depth_to,v,m.unit,level)});profile.appendChild(track)});requestAnimationFrame(()=>applyScale(autoFit))}
  selector.querySelectorAll('input[type=checkbox]').forEach(e=>e.addEventListener('change',()=>render(!profilePrefs.userScaled)));
  selector.querySelector('.profile-vscale').addEventListener('input',()=>{profilePrefs.userScaled=true;applyScale(false)});
  selector.querySelector('.profile-wscale').addEventListener('input',()=>{profilePrefs.wscale=+selector.querySelector('.profile-wscale').value;render(false)});
  render(!profilePrefs.userScaled);
 }
 const original=window.createBoreholeProfile;if(typeof original==='function')window.createBoreholeProfile=function(point,container,standards){original(point,container,standards);const sections=container.querySelectorAll('.borehole-section'),section=sections[sections.length-1],profile=section?.querySelector('.borehole-profile');if(!profile)return;const depths=[...(point.geology||[]).map(x=>+x.to||0),...(point.samples||[]).map(x=>+x.depth_to||0),...(point.field_screening||[]).map(x=>+x.depth_to||0)],maxDepth=Math.max(...depths,0);if(maxDepth<=0)return;profile.classList.add('professional-profile','multi-track-profile');addProfileTracks(point,section,profile,standards,maxDepth);const legend=section.querySelector('.profile-legend');if(legend)legend.remove()};
})();