(()=>{
const d=window.siteData,$=id=>document.getElementById(id),num=v=>typeof v==='number'&&Number.isFinite(v),fmt=(v,n=2)=>num(v)?v.toFixed(n):'—',safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!d.soilPoints.length&&!d.wells.length){$('dash-map').innerHTML='<div class="upload-empty"><strong>尚未載入調查資料</strong><span>請按頁首「上傳 Excel」選取調查活頁簿。</span></div>';$('dash-counts').textContent='土壤 0 點 · 監測井 0 口';$('dash-location-title').textContent='點位資料';$('dash-location').innerHTML='<p class="upload-empty-text">匯入 Excel 後會顯示土壤剖面與監測井資料。</p>';$('dash-oil-summary').textContent='等待浮油量測資料';$('dash-oil-selected').innerHTML='<p class="upload-empty-text">匯入後可用時間滑桿查看六井狀態。</p>';return}
const oilIDs=[...new Set(d.records.map(r=>r.well))],labMax=new Map(),labSND=new Set();for(const r of d.soilResults){if(num(r.lab))labMax.set(r.id,Math.max(r.lab,labMax.get(r.id)??-Infinity));if(r.lab==='SND')labSND.add(r.id)}
const pts=[...d.soilPoints,...d.wells];
// TWD97 TM2 (EPSG:3826) to WGS84 for Web Mercator imagery.
function toLonLat(east,north){const a=6378137,f=1/298.257222101,k=.9999,e2=f*(2-f),ep2=e2/(1-e2),m=north/k,mu=m/(a*(1-e2/4-3*e2**2/64-5*e2**3/256)),e1=(1-Math.sqrt(1-e2))/(1+Math.sqrt(1-e2)),p=mu+(3*e1/2-27*e1**3/32)*Math.sin(2*mu)+(21*e1**2/16-55*e1**4/32)*Math.sin(4*mu)+(151*e1**3/96)*Math.sin(6*mu)+(1097*e1**4/512)*Math.sin(8*mu),c=ep2*Math.cos(p)**2,t=Math.tan(p)**2,n=a/Math.sqrt(1-e2*Math.sin(p)**2),r=a*(1-e2)/(1-e2*Math.sin(p)**2)**1.5,D=(east-250000)/(n*k),lat=p-n*Math.tan(p)/r*(D**2/2-(5+3*t+10*c-4*c**2-9*ep2)*D**4/24+(61+90*t+298*c+45*t*t-252*ep2-3*c*c)*D**6/720),lon=121*Math.PI/180+(D-(1+2*t+c)*D**3/6+(5-2*c+28*t-3*c*c+8*ep2+24*t*t)*D**5/120)/Math.cos(p);return {lat:lat*180/Math.PI,lon:lon*180/Math.PI}}
const geo=new Map(pts.map(p=>[p.id,toLonLat(p.east,p.north)])),center={lat:pts.reduce((v,p)=>v+geo.get(p.id).lat,0)/pts.length,lon:pts.reduce((v,p)=>v+geo.get(p.id).lon,0)/pts.length};
const MAP_MIN_ZOOM=15,MAP_MAX_ZOOM=19;const mapState={lat:center.lat,lon:center.lon,zoom:17},mapEl=$('dash-map');mapEl.innerHTML='<div class="map-tiles"></div><div class="map-markers"></div><div class="map-controls"><button type="button" data-zoom="1" aria-label="放大地圖">＋</button><button type="button" data-zoom="-1" aria-label="縮小地圖">−</button><button type="button" data-fit="1" aria-label="顯示全部點位">⌖</button></div><div class="map-attribution">衛星影像 © Esri、Maxar、Earthstar Geographics、GIS User Community</div>';
const world=(lat,lon,z)=>{const size=256*2**z,s=Math.sin(Math.max(-85,Math.min(85,lat))*Math.PI/180);return {x:(lon+180)/360*size,y:(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*size}},unworld=(x,y,z)=>{const size=256*2**z;return {lon:x/size*360-180,lat:Math.atan(Math.sinh(Math.PI*(1-2*y/size)))*180/Math.PI}};
function paintMap(){const box=mapEl.getBoundingClientRect(),w=box.width,h=box.height;if(!w||!h)return;const z=mapState.zoom,mid=world(mapState.lat,mapState.lon,z),left=mid.x-w/2,top=mid.y-h/2,x0=Math.floor(left/256),x1=Math.floor((left+w)/256),y0=Math.floor(top/256),y1=Math.floor((top+h)/256),tiles=[];for(let x=x0;x<=x1;x++)for(let y=y0;y<=y1;y++){if(x<0||y<0||x>=2**z||y>=2**z)continue;tiles.push(`<img alt="" draggable="false" src="https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${z}/${y}/${x}" style="left:${x*256-left}px;top:${y*256-top}px">`)}mapEl.querySelector('.map-tiles').innerHTML=tiles.join('');
const q=$('dash-search').value.trim().toLowerCase(),showSoil=$('dash-soil-layer').checked,showWell=$('dash-well-layer').checked;const group=(items,kind)=>items.filter(p=>!q||p.id.toLowerCase().includes(q)).map(p=>{const v=world(geo.get(p.id).lat,geo.get(p.id).lon,z),x=v.x-left,y=v.y-top,active=place.kind===kind&&place.id===p.id,color=kind==='well'?(oilIDs.includes(p.id)?'#d88b4d':'#419b5c'):(labMax.get(p.id)>1000?'#c7633b':labMax.get(p.id)>=500?'#e7a75a':labMax.has(p.id)?'#27864b':labSND.has(p.id)?'#78b987':'#9fbba4');return `<button type="button" class="map-pin ${kind} ${active?'active':''}" style="left:${x}px;top:${y}px;--pin:${color}" data-kind="${kind}" data-id="${safe(p.id)}" aria-label="查看 ${safe(p.id)}"><i></i><span>${safe(p.id)}</span></button>`}).join('');mapEl.querySelector('.map-markers').innerHTML=(showSoil?group(d.soilPoints,'soil'):'')+(showWell?group(d.wells,'well'):'');mapEl.classList.toggle('map-detailed',z>=18);mapEl.querySelector('[data-zoom="1"]').disabled=z>=MAP_MAX_ZOOM;mapEl.querySelector('[data-zoom="-1"]').disabled=z<=MAP_MIN_ZOOM;mapEl.querySelectorAll('.map-pin').forEach(pin=>pin.onclick=()=>select(pin.dataset.kind,pin.dataset.id))}
function mapZoom(delta,atX=mapEl.clientWidth/2,atY=mapEl.clientHeight/2){const z=Math.min(MAP_MAX_ZOOM,Math.max(MAP_MIN_ZOOM,mapState.zoom+delta));if(z===mapState.zoom)return;const old=world(mapState.lat,mapState.lon,mapState.zoom),anchor=unworld(old.x+atX-mapEl.clientWidth/2,old.y+atY-mapEl.clientHeight/2,mapState.zoom),newAnchor=world(anchor.lat,anchor.lon,z),newCenter=unworld(newAnchor.x-(atX-mapEl.clientWidth/2),newAnchor.y-(atY-mapEl.clientHeight/2),z);Object.assign(mapState,newCenter,{zoom:z});paintMap()}
mapEl.querySelector('.map-controls').onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.fit){Object.assign(mapState,center,{zoom:17});paintMap()}else mapZoom(Number(button.dataset.zoom))};mapEl.addEventListener('wheel',e=>{e.preventDefault();const rect=mapEl.getBoundingClientRect();mapZoom(e.deltaY<0?1:-1,e.clientX-rect.left,e.clientY-rect.top)},{passive:false});let drag=null;mapEl.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,origin:world(mapState.lat,mapState.lon,mapState.zoom)};mapEl.setPointerCapture(e.pointerId);mapEl.classList.add('dragging')});mapEl.addEventListener('pointermove',e=>{if(!drag)return;Object.assign(mapState,unworld(drag.origin.x-(e.clientX-drag.x),drag.origin.y-(e.clientY-drag.y),mapState.zoom));paintMap()});mapEl.addEventListener('pointerup',()=>{drag=null;mapEl.classList.remove('dragging')});new ResizeObserver(paintMap).observe(mapEl);
const timeline=[...new Set(d.records.map(r=>r.date+' '+(r.time||'00:00:00')))].sort();if(!timeline.length)timeline.push(new Date().toISOString().slice(0,10)+' 00:00:00');let timeIndex=timeline.length-1,place={kind:d.soilPoints.length?'soil':'well',id:d.soilPoints[0]?.id||d.wells[0]?.id},selectedOil=oilIDs[0]||d.wells[0]?.id||'',wellHistoryDate='';$('dash-date').value=timeline[timeIndex].slice(0,10);$('dash-time-slider').max=String(timeIndex);$('dash-time-slider').value=String(timeIndex);$('dash-time-start').textContent=timeline[0].slice(0,16);$('dash-time-end').textContent=timeline.at(-1).slice(0,16);
const getRecord=(id,selected=timeline[timeIndex])=>{const base=new Date(selected.replace(' ','T')+'Z');return d.records.map((r,i)=>({...r,i})).filter(r=>r.well===id&&r.date+' '+(r.time||'00:00:00')<=selected&&(base-new Date(r.date+'T'+(r.time||'00:00:00')+'Z'))/86400000<=10).sort((a,b)=>b.date.localeCompare(a.date)||b.time.localeCompare(a.time)||a.i-b.i)[0]||null};
function setTimeIndex(i){timeIndex=Math.min(timeline.length-1,Math.max(0,i));$('dash-time-slider').value=String(timeIndex);$('dash-date').value=timeline[timeIndex].slice(0,10);renderOil()}
const thick=r=>r?(num(r.thickness)?r.thickness:num(r.oilDepth)&&num(r.waterDepth)?r.waterDepth-r.oilDepth:NaN):NaN;
function select(kind,id){place={kind,id};if(kind==='well'&&oilIDs.includes(id))selectedOil=id;renderMap();renderLocation();renderOil()}
function renderMap(){paintMap();const q=$('dash-search').value.trim().toLowerCase(),showSoil=$('dash-soil-layer').checked,showWell=$('dash-well-layer').checked;
$('dash-counts').textContent=`● 土壤 ${d.soilPoints.length} 點（${[...labMax.values()].filter(v=>v>1000).length} 點超標、${labSND.size} 點含 SND）  ■ 監測井 ${d.wells.length} 口`;
const soils=d.soilPoints.slice().sort((a,b)=>(labMax.get(b.id)??-1)-(labMax.get(a.id)??-1)),wellList=d.wells.slice().sort((a,b)=>Number(oilIDs.includes(b.id))-Number(oilIDs.includes(a.id)));$('dash-list').innerHTML=[...(showSoil?soils.map(p=>({kind:'soil',...p})):[]),...(showWell?wellList.map(p=>({kind:'well',...p})):[])].filter(p=>!q||p.id.toLowerCase().includes(q)).map(p=>`<button class="${place.kind===p.kind&&place.id===p.id?'active':''}" data-kind="${p.kind}" data-id="${safe(p.id)}"><span>${safe(p.id)}</span><em>${p.kind==='soil'?(labMax.has(p.id)?Number(labMax.get(p.id)).toLocaleString()+' mg/kg':labSND.has(p.id)?'SND':'—'):(oilIDs.includes(p.id)?'曾測得浮油':'井位')}</em></button>`).join('');$('dash-list').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.kind,b.dataset.id))}
const geologyColor=value=>{const t=String(value||'');if(/AC|瀝青/i.test(t))return '#8a969b';let family=/灰黑|黑灰|黑色/.test(t)?'charcoal':/灰褐|褐灰|棕灰|灰棕/.test(t)?'mix':/灰色/.test(t)?'gray':/紅土/.test(t)?'red':/黃/.test(t)?'yellow':/棕/.test(t)?'brown':'ochre';const texture=/黏/.test(t)?2:/坋|砏|粉/.test(t)?1:0;const colors={charcoal:['#aab0b3','#b8bdc0','#c5c8c9'],mix:['#c9c2b9','#d5cdc1','#ded5c8'],gray:['#cbd5d9','#dae1e3','#e3e8e9'],red:['#dcae9b','#e6beac','#ebc9bb'],yellow:['#e8d69d','#eedfae','#f1e7c3'],brown:['#cbae8d','#d8bc9a','#e2cbaa'],ochre:['#d8b89a','#e3c6a8','#e9d4ba']};return colors[family][texture]};
function renderLocation(){if(place.kind==='soil')renderSoil();else renderWell()}
const soilDefs=[['深度','axis','38px'],['地層描述','geology','146px'],['TPH 實驗室分析 (mg/kg)','lab','95px'],['PID (ppmV)','pid','66px'],['FID (ppmV)','fid','72px'],['內插採用值 (mg/kg)','interpolated','90px'],['TPH TEST KIT 柴 (mg/kg)','diesel','84px'],['TPH TEST KIT 航 (mg/kg)','aviation','84px']];
const visibleSoil=new Set(['geology','lab','pid','fid','interpolated']);
$('soil-columns').innerHTML=soilDefs.slice(1).map(([label,key])=>`<label><input type="checkbox" value="${key}" ${visibleSoil.has(key)?'checked':''}> ${safe(label.replace(/ \(.*?\)/g,''))}</label>`).join('');
$('soil-columns').onchange=e=>{if(e.target.type!=='checkbox')return;if(e.target.checked)visibleSoil.add(e.target.value);else visibleSoil.delete(e.target.value);renderSoil()};
function renderSoil(){const id=place.id,rows=d.soilResults.filter(v=>v.id===id),layers=d.strata.filter(v=>v.id===id),lab=rows.filter(r=>num(r.lab)||r.lab==='SND'),maxDepth=Math.max(0,...rows.map(r=>r.to))||Math.max(1,...layers.map(r=>r.to)),top=v=>Math.max(0,Math.min(100,v/maxDepth*100));$('soil-columns').hidden=false;$('dash-location-title').textContent=id+' · 土壤剖面';$('dash-location-kind').textContent=`單位 mg/kg · 深度 0–${Number(maxDepth.toFixed(2))} m`;
const defs=soilDefs.filter(([,key])=>key==='axis'||visibleSoil.has(key));const step=maxDepth<=4?0.5:1,ticks=[];for(let v=0;v<maxDepth-0.05;v+=step)ticks.push(v);ticks.push(maxDepth);
const axis=ticks.map(v=>`<span style="top:${top(v)}%">${Number(v.toFixed(2))} m</span>`).join('');
const rect=(r,content,klass,background,title)=>{const from=Math.max(0,r.from),to=Math.min(maxDepth,r.to);return to<=from?'':`<div class="matrix-cell ${klass}" style="top:${top(from)}%;height:${Math.max(1.7,(to-from)/maxDepth*100)}%;${background?'background:'+background+';':''}" title="${safe(title)}">${content}</div>`};
const geology=layers.map(r=>rect(r,`${safe(r.material)}<small>${fmt(r.from,1)}–${fmt(Math.min(r.to,maxDepth),1)} m</small>`,'geology',geologyColor(r.material),`${r.material} · ${r.from}–${Math.min(r.to,maxDepth)} m`)).join('');
const labCells=rows.map(r=>{if(r.lab===null||r.lab===undefined)return rect(r,'','empty-cell','',`${r.from}–${r.to} m 無實驗室 TPH`);if(r.lab==='SND')return rect(r,'SND','value lab-snd','',`${r.from}–${r.to} m · SND，低於 200 mg/kg`);const v=Number(r.lab),flag=v>1000?'<span class="flag">超標</span>':v>=500?'<span class="flag">≥1/2 標準</span>':'';return rect(r,`${v.toLocaleString()}${flag}`,`value ${v>1000?'lab-high':v>=500?'lab-half':'lab-normal'}`,'',`${r.from}–${r.to} m · TPH ${v} mg/kg`)}).join('');
const numericLane=key=>rows.map(r=>rect(r,num(r[key])?Number(r[key]).toLocaleString('zh-TW',{maximumFractionDigits:3}):'',num(r[key])?'value':'empty-cell','',`${r.from}–${r.to} m · ${key}: ${num(r[key])?r[key]:'無數據'}`)).join('');
const lanes={axis,geology,lab:labCells,pid:numericLane('pid'),fid:numericLane('fid'),interpolated:numericLane('interpolated'),diesel:numericLane('diesel'),aviation:numericLane('aviation')};
const matrix=defs.map(([label])=>`<div class="matrix-head">${label}</div>`).join('')+defs.map(([,key])=>`<div class="matrix-lane ${key}">${lanes[key]}</div>`).join('');
$('dash-location').innerHTML=`<div class="soil-inline-summary"><span>實驗室結果 <b>${lab.length}</b> 筆</span><span>最高實測 TPH <b>${labMax.has(id)?Number(labMax.get(id)).toLocaleString():labSND.has(id)?'SND':'—'}</b></span><span>SND＝低於 200 mg/kg</span></div><div class="matrix-wrap"><div class="soil-matrix" style="grid-template-columns:${defs.map(x=>x[1]==='axis'?x[2]:`minmax(${x[2]},${parseInt(x[2])/85}fr)`).join(' ')};min-width:${defs.reduce((n,x)=>n+parseInt(x[2]),0)}px">${matrix}</div></div><p class="matrix-note">數值與地層按深度對齊；空白表示該欄無資料。內插值與實驗室結果分開呈現。</p>`}
function renderWell(){$('soil-columns').hidden=true;const p=d.wells.find(w=>w.id===place.id),hasOil=oilIDs.includes(p.id),r=getRecord(p.id),history=d.records.filter(v=>v.well===p.id).sort((a,b)=>b.date.localeCompare(a.date)||b.time.localeCompare(a.time)),shown=wellHistoryDate?history.filter(v=>v.date===wellHistoryDate):history;
$('dash-location-title').textContent=p.id+' · 地下水井';$('dash-location-kind').textContent=hasOil?'曾測得浮油':'未列浮油紀錄';$('dash-location').innerHTML=`<div class="dash-metrics"><div><b>${fmt(p.toc,3)}</b><small>井頂高程 · m MSL</small></div><div><b>${fmt(p.depth,2)}</b><small>井深 · m</small></div></div><dl class="dash-well-list"><dt>TWD97 X / Y</dt><dd>${fmt(p.east,3)} / ${fmt(p.north,3)}</dd><dt>井徑</dt><dd>${p.diameter??'—'} 吋</dd><dt>井篩深度</dt><dd>${fmt(p.screenTop,2)}–${fmt(p.screenBottom,2)} m bgs</dd><dt>水力傳導係數 K</dt><dd>${num(p.k)?p.k:'—'} cm/s</dd><dt>所選時間浮油厚度</dt><dd>${r?fmt(thick(r),3)+' m':'前10天內無數據'}</dd><dt>量測時間</dt><dd>${r?r.date+' '+(r.time||''):'—'}</dd></dl><div class="well-history-head"><strong>浮油量測紀錄 · ${shown.length} 筆</strong><div><label for="well-history-date">日期</label><input id="well-history-date" type="date" value="${wellHistoryDate}" aria-label="依日期篩選該井量測紀錄"><button id="well-history-all" type="button" ${wellHistoryDate?'':'disabled'}>全部日期</button></div></div>${shown.length?`<div class="well-history-wrap"><table class="well-history"><thead><tr><th>日期</th><th>時間</th><th>油位 m</th><th>水位 m</th><th>油厚 m</th><th>備註</th></tr></thead><tbody>${shown.map(v=>`<tr class="${v.date===$('dash-date').value?'selected-date':''}"><td>${safe(v.date)}</td><td>${safe(v.time||'—')}</td><td>${fmt(v.oilDepth,3)}</td><td>${fmt(v.waterDepth,3)}</td><td><b>${fmt(thick(v),3)}</b></td><td>${safe(v.note||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="note">此井在提供的浮油量測資料中無紀錄；「無紀錄」不等於證實無浮油。</p>'}<p class="note">地下水檢測結果工作表目前無紀錄。上表逐筆顯示量測，不合併同日資料。</p>`;
$('well-history-date').onchange=e=>{wellHistoryDate=e.target.value;if(wellHistoryDate){const i=timeline.findLastIndex(t=>t.slice(0,10)<=wellHistoryDate);setTimeIndex(Math.max(0,i))}else renderWell()};$('well-history-all').onclick=()=>{wellHistoryDate='';renderWell()}}
function renderOil(){const selected=timeline[timeIndex],date=selected.slice(0,10),rec=oilIDs.map(id=>({id,r:getRecord(id)}));$('dash-time').textContent=selected.slice(0,16);$('dash-time-slider').setAttribute('aria-valuetext',selected);$('dash-oil-summary').textContent=`${date} ${selected.slice(11,16)} · ${rec.filter(v=>v.r&&v.r.date===date).length} 井當日資料 · ${rec.filter(v=>v.r&&v.r.date!==date).length} 井前10天歷史資料`;
$('dash-oil-cards').innerHTML=rec.map(({id,r})=>{const w=d.wells.find(v=>v.id===id),t=thick(r),stale=r&&r.date!==date;return `<button data-id="${safe(id)}" class="${selectedOil===id?'active':''} ${stale?'stale':''}" aria-label="查看 ${safe(id)} 浮油"><b>${safe(id)}</b><div class="dash-mini">${w?`<i class="screen" style="top:${w.screenTop/8*100}%;height:${(w.screenBottom-w.screenTop)/8*100}%"></i>`:''}${r&&num(r.oilDepth)&&num(r.waterDepth)?`<i class="oilband" style="top:${r.oilDepth/8*100}%;height:${Math.max(1,t/8*100)}%"></i><i class="waterline" style="top:${r.waterDepth/8*100}%"></i>`:''}</div><strong>${r?fmt(t,3)+' m':'無數據'}</strong><small>${r?(stale?'歷史 · ':'當日 · ')+r.date+' '+(r.time||'').slice(0,5):'前10天內'}</small></button>`}).join('');$('dash-oil-cards').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedOil=b.dataset.id;select('well',selectedOil)});
const all=d.records.filter(r=>r.well===selectedOil&&r.date+' '+(r.time||'00:00:00')<=selected).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)),recent=all.slice(-14),maximum=Math.max(1.5,...recent.map(r=>thick(r))),dates=recent.map(r=>Date.parse(r.date+'T'+(r.time||'12:00').slice(0,5)+':00Z')),first=dates[0],span=(dates.at(-1)-first)||1,xAt=i=>recent.length===1?160:18+(dates[i]-first)/span*282,chart=recent.map((r,i)=>`${xAt(i).toFixed(1)},${(92-thick(r)/maximum*80).toFixed(1)}`).join(' '),months=[...new Map(recent.map((r,i)=>[r.date.slice(0,7),i]).reverse()).entries()].sort((a,b)=>a[1]-b[1]),monthTicks=months.filter((_,i)=>i===0||i===months.length-1||months.length<=5||i%Math.ceil(months.length/4)===0),current=getRecord(selectedOil);$('dash-oil-selected').innerHTML=`<h4>${safe(selectedOil)} · 厚度歷時</h4><div class="oil-values"><span>油位 ${current?fmt(current.oilDepth,3):'—'} m</span><span>水位 ${current?fmt(current.waterDepth,3):'—'} m</span><span>${current?safe(current.note||''):'—'}</span></div><svg viewBox="0 0 320 120" role="img" aria-label="${safe(selectedOil)} 最近量測厚度折線圖，橫軸為月份"><line x1="17" y1="93" x2="305" y2="93" stroke="#a9bfc4"/>${monthTicks.map(([month,i])=>`<line x1="${xAt(i)}" y1="16" x2="${xAt(i)}" y2="93" stroke="#e3ecee"/><text x="${Math.max(18,Math.min(288,xAt(i)-9))}" y="111" font-size="10" fill="#55747e">${month.slice(5)}月</text>`).join('')}<polyline points="${chart}" fill="none" stroke="#c27944" stroke-width="2.5" stroke-linejoin="round"/>${recent.map((r,i)=>{const x=xAt(i),y=92-thick(r)/maximum*80;return `<circle cx="${x}" cy="${y}" r="3.5" fill="#c27944"><title>${r.date} ${r.time}：${fmt(thick(r),3)} m</title></circle>`}).join('')}</svg><p>卡片顯示滑桿時間之前最近一筆；無當日資料時取前10天最近一筆，斜線表示歷史資料。井篩與油水位深度基準不同，剖面位置僅供對照。</p>`;
if(place.kind==='well')renderWell()}
$('dash-soil-layer').onchange=renderMap;$('dash-well-layer').onchange=renderMap;$('dash-search').oninput=renderMap;$('dash-time-slider').oninput=e=>setTimeIndex(Number(e.target.value));renderMap();renderLocation();renderOil();
})();
